import type {
  Organization,
  Team,
  Member,
  Repo,
  PullRequest,
  PRAssessment,
  PolicyPack,
  Control,
  RepoBinding,
  AuditEntry,
  DependencyGraph,
  Issue,
} from "@/types";

// ─── Organization ───────────────────────────────────────────────────────────

export const mockOrg: Organization = {
  id: "org-001",
  did: "did:plc:acmehealth7x2kqmn9pltrs44e",
  handle: "acmehealth.tngl.sh",
  name: "Acme Health",
  description: "Health-tech startup building secure, GDPR-compliant patient data platforms. Subject to GDPR and ISO 27001.",
  createdAt: "2023-06-15T10:00:00Z",
  stats: {
    repos: 3,
    members: 3,
    teams: 1,
    openPRs: 3,
  },
};

// ─── Teams ───────────────────────────────────────────────────────────────────

export const mockTeams: Team[] = [
  {
    id: "team-001",
    name: "Engineering",
    slug: "engineering",
    description: "Full-stack engineering, compliance, and security for all Acme Health repositories.",
    memberCount: 3,
    repoCount: 3,
    members: ["member-001", "member-002", "member-003"],
    repos: ["repo-001", "repo-002", "repo-003"],
  },
];

// ─── Members ─────────────────────────────────────────────────────────────────

export const mockMembers: Member[] = [
  {
    id: "member-001",
    did: "did:plc:alice7xmq2kltrs9pnv44abc",
    handle: "alice.tngl.sh",
    displayName: "Alice Chen",
    role: "owner",
    teams: ["team-001"],
    lastActive: "2026-06-24T09:15:00Z",
    approvalCount: 47,
  },
  {
    id: "member-002",
    did: "did:plc:bob8yn3kqtr7plm55def",
    handle: "bob.tngl.sh",
    displayName: "Bob Martinez",
    role: "developer",
    teams: ["team-001"],
    lastActive: "2026-06-23T16:42:00Z",
    approvalCount: 31,
  },
  {
    id: "member-003",
    did: "did:plc:carol9zp4lrus8qmn66ghi",
    handle: "carol.tngl.sh",
    displayName: "Carol Nguyen",
    role: "dpo",
    teams: ["team-001"],
    lastActive: "2026-06-24T08:00:00Z",
    approvalCount: 22,
  },
];

// ─── Repos ───────────────────────────────────────────────────────────────────

export const mockRepos: Repo[] = [
  {
    id: "repo-001",
    did: "did:plc:repo7xacme1patient22abc",
    name: "patient-service",
    slug: "patient-service",
    description: "Core patient data service. Handles patient profiles, medical records, and GDPR data portability requests. Contains highly sensitive PII and PHI.",
    language: "Go",
    complianceStatus: "non-compliant",
    riskTier: "high",
    dataClassification: "confidential",
    stars: 42,
    forks: 7,
    openPRs: 1,
    lastActivity: "2026-06-24T09:15:00Z",
    policyPacks: ["pack-001", "pack-002"],
    regulations: ["GDPR", "ISO 27001"],
    codeOwners: [
      { pattern: "**", owners: ["@alice.tngl.sh", "@bob.tngl.sh"], teamOwners: ["@engineering"] },
      { pattern: "api/**", owners: ["@bob.tngl.sh"], teamOwners: ["@engineering"] },
      { pattern: "models/patient*.go", owners: ["@carol.tngl.sh"], teamOwners: ["@engineering"] },
    ],
    teamId: "team-001",
  },
  {
    id: "repo-002",
    did: "did:plc:repo8yacme2billing33def",
    name: "billing-service",
    slug: "billing-service",
    description: "Patient billing and insurance claim processing. Integrates with Stripe for payment handling. ISO 27001 certified.",
    language: "TypeScript",
    complianceStatus: "compliant",
    riskTier: "high",
    dataClassification: "confidential",
    stars: 88,
    forks: 12,
    openPRs: 1,
    lastActivity: "2026-06-23T16:42:00Z",
    policyPacks: ["pack-001"],
    regulations: ["ISO 27001"],
    codeOwners: [
      { pattern: "**", owners: ["@alice.tngl.sh"], teamOwners: ["@engineering"] },
      { pattern: "src/stripe/**", owners: ["@bob.tngl.sh"], teamOwners: ["@engineering"] },
    ],
    teamId: "team-001",
  },
  {
    id: "repo-003",
    did: "did:plc:repo9zacme3auth44ghi",
    name: "auth-service",
    slug: "auth-service",
    description: "Authentication and authorization service. Handles SSO, MFA enrollment, and session management for all internal services.",
    language: "Go",
    complianceStatus: "at-risk",
    riskTier: "high",
    dataClassification: "internal",
    stars: 67,
    forks: 9,
    openPRs: 1,
    lastActivity: "2026-06-22T11:30:00Z",
    policyPacks: ["pack-001"],
    regulations: ["ISO 27001"],
    codeOwners: [
      { pattern: "**", owners: ["@carol.tngl.sh"], teamOwners: ["@engineering"] },
      { pattern: "endpoints/**", owners: ["@bob.tngl.sh", "@carol.tngl.sh"], teamOwners: ["@engineering"] },
    ],
    teamId: "team-001",
  },
];

// ─── Controls ─────────────────────────────────────────────────────────────────

export const mockControls: Record<string, Control[]> = {
  "pack-001": [
    { id: "ACCESS-1", name: "Access Control Policy", description: "Establish, document, and review access control policy.", severity: "high", automated: false, policyPackId: "pack-001", category: "Access Control", reference: "ISO 27001:2022 A.9.1" },
    { id: "ACCESS-2", name: "Least Privilege Enforcement", description: "Users granted minimum access required for their role.", severity: "high", automated: true, policyPackId: "pack-001", category: "Access Control", reference: "ISO 27001:2022 A.9.2" },
    { id: "CHANGE-1", name: "Change Management Process", description: "All changes documented, reviewed and approved before deployment.", severity: "medium", automated: true, policyPackId: "pack-001", category: "Change Management", reference: "ISO 27001:2022 A.12.1" },
    { id: "CHANGE-2", name: "Rollback Capability", description: "All deployments must have documented rollback procedures.", severity: "medium", automated: false, policyPackId: "pack-001", category: "Change Management", reference: "ISO 27001:2022 A.12.1" },
    { id: "VULN-1", name: "Dependency Vulnerability Scan", description: "OSV scan required on every PR. No critical CVEs unmitigated.", severity: "critical", automated: true, policyPackId: "pack-001", category: "Vulnerability Management", reference: "ISO 27001:2022 A.12.6" },
    { id: "VULN-2", name: "SAST Scan Required", description: "Static analysis must pass before merge. Semgrep ruleset enforced.", severity: "high", automated: true, policyPackId: "pack-001", category: "Vulnerability Management", reference: "ISO 27001:2022 A.14.2" },
    { id: "VULN-3", name: "Secret Scanning", description: "No secrets or credentials may be committed to source control.", severity: "critical", automated: true, policyPackId: "pack-001", category: "Vulnerability Management", reference: "ISO 27001:2022 A.14.2" },
    { id: "OWN-1", name: "Code Owner Review", description: "Changes to owned paths require approval from designated code owner.", severity: "high", automated: true, policyPackId: "pack-001", category: "Ownership", reference: "ISO 27001:2022 A.6.1" },
    { id: "OWN-2", name: "Security Lead Approval for Auth Changes", description: "Any changes to authentication or authorization paths require security-lead approval.", severity: "high", automated: true, policyPackId: "pack-001", category: "Ownership", reference: "ISO 27001:2022 A.9.4" },
    { id: "CLASS-1", name: "Data Classification Required", description: "Repository must have data classification set before merge gates are active.", severity: "medium", automated: false, policyPackId: "pack-001", category: "Asset Management", reference: "ISO 27001:2022 A.8.3" },
    { id: "DOC-1", name: "Change Documented", description: "PR must reference a ticket or design document.", severity: "low", automated: true, policyPackId: "pack-001", category: "Documentation", reference: "ISO 27001:2022 A.12.1" },
    { id: "AUDIT-1", name: "Audit Log Immutability", description: "All compliance actions written to immutable AT Protocol audit log.", severity: "high", automated: true, policyPackId: "pack-001", category: "Audit", reference: "ISO 27001:2022 A.12.4" },
  ],
  "pack-002": [
    { id: "GDPR-1", name: "Data Minimization", description: "Personal data collection limited to what is necessary.", severity: "critical", automated: false, policyPackId: "pack-002", category: "Data Processing", reference: "GDPR Art. 5(1)(c)" },
    { id: "GDPR-2", name: "Data Protection by Design", description: "Implement data protection by design and by default.", severity: "high", automated: false, policyPackId: "pack-002", category: "Privacy Engineering", reference: "GDPR Art. 25" },
    { id: "GDPR-3", name: "Security of Processing", description: "Implement appropriate technical and organizational security measures.", severity: "critical", automated: true, policyPackId: "pack-002", category: "Security", reference: "GDPR Art. 32" },
    { id: "GDPR-4", name: "Right to Erasure", description: "Implement mechanisms to fulfill data erasure requests.", severity: "high", automated: false, policyPackId: "pack-002", category: "Data Subject Rights", reference: "GDPR Art. 17" },
    { id: "GDPR-5", name: "Breach Notification", description: "Notify supervisory authority of personal data breaches within 72h.", severity: "critical", automated: false, policyPackId: "pack-002", category: "Incident Response", reference: "GDPR Art. 33" },
    { id: "GDPR-6", name: "Data Retention Policy", description: "PII must not be retained beyond the defined retention period.", severity: "high", automated: true, policyPackId: "pack-002", category: "Data Lifecycle", reference: "GDPR Art. 5(1)(e)" },
    { id: "GDPR-7", name: "DPO Approval for PII Changes", description: "Any code changes affecting PII fields or processing logic require DPO approval.", severity: "critical", automated: false, policyPackId: "pack-002", category: "Approval", reference: "GDPR Art. 37-39" },
    { id: "GDPR-8", name: "Encryption at Rest", description: "All PII fields must be encrypted at rest using approved algorithms.", severity: "critical", automated: true, policyPackId: "pack-002", category: "Cryptography", reference: "GDPR Art. 32(1)(a)" },
  ],
};

// ─── Policy Packs ─────────────────────────────────────────────────────────────

export const mockPolicyPacks: PolicyPack[] = [
  {
    id: "pack-001",
    name: "ISO 27001 Base",
    framework: "ISO 27001",
    version: "2022",
    description: "ISO 27001:2022 baseline controls for information security management. Mandatory for all Acme Health repositories.",
    controlCount: 12,
    repoCount: 3,
    controls: mockControls["pack-001"],
    createdAt: "2023-09-01T00:00:00Z",
    updatedAt: "2025-01-15T00:00:00Z",
  },
  {
    id: "pack-002",
    name: "GDPR Data Pack",
    framework: "GDPR",
    version: "2018",
    description: "EU GDPR controls for patient data handling, processing lawfulness, DPO approval workflows, and breach notification.",
    controlCount: 8,
    repoCount: 1,
    controls: mockControls["pack-002"],
    createdAt: "2023-09-01T00:00:00Z",
    updatedAt: "2024-11-20T00:00:00Z",
  },
];

// ─── Repo Bindings ────────────────────────────────────────────────────────────

export const mockRepoBindings: RepoBinding[] = [
  { id: "bind-001", repoId: "repo-001", repoSlug: "patient-service", policyPackId: "pack-001", policyPackName: "ISO 27001 Base", boundAt: "2023-10-01T00:00:00Z", boundBy: "@carol.tngl.sh" },
  { id: "bind-002", repoId: "repo-001", repoSlug: "patient-service", policyPackId: "pack-002", policyPackName: "GDPR Data Pack", boundAt: "2023-10-01T00:00:00Z", boundBy: "@carol.tngl.sh" },
  { id: "bind-003", repoId: "repo-002", repoSlug: "billing-service", policyPackId: "pack-001", policyPackName: "ISO 27001 Base", boundAt: "2023-10-01T00:00:00Z", boundBy: "@carol.tngl.sh" },
  { id: "bind-004", repoId: "repo-003", repoSlug: "auth-service", policyPackId: "pack-001", policyPackName: "ISO 27001 Base", boundAt: "2023-10-01T00:00:00Z", boundBy: "@carol.tngl.sh" },
];

// ─── Pull Request Assessments ─────────────────────────────────────────────────

const assessment001: PRAssessment = {
  id: "assess-001",
  prId: "pr-001",
  assessedAt: "2026-06-24T08:30:00Z",
  assessedBy: "did:plc:agent7xcompliancerunner22abc",
  mergeGate: "blocked",
  riskTier: "high",
  riskSummary: "This PR adds a patient data export endpoint that returns raw PII including medical records and GDPR-protected fields. SAST found 2 findings including a leaked EXPORT_ENCRYPTION_KEY. OSV detected a critical CVE in csv-lib@1.2.0 (CVE-2024-38517). DPO approval is required under GDPR-7. This PR is linked to incident INC-7.",
  complianceScore: 41,
  controlEvaluations: [
    { id: "eval-001-1", controlId: "GDPR-7", controlName: "DPO Approval for PII Changes", policyPack: "GDPR Data Pack", severity: "critical", status: "fail", detail: "PII export endpoint added without DPO sign-off. carol.tngl.sh approval pending.", automatedCheck: false },
    { id: "eval-001-2", controlId: "VULN-1", controlName: "Dependency Vulnerability Scan", policyPack: "ISO 27001 Base", severity: "critical", status: "fail", detail: "csv-lib@1.2.0 has critical CVE-2024-38517 (CVSS 9.8). Fix required before merge.", automatedCheck: true },
    { id: "eval-001-3", controlId: "VULN-2", controlName: "SAST Scan Required", policyPack: "ISO 27001 Base", severity: "high", status: "fail", detail: "Semgrep found 2 findings: EXPORT_ENCRYPTION_KEY leaked in config file, unsafe CSV parsing.", automatedCheck: true },
    { id: "eval-001-4", controlId: "VULN-3", controlName: "Secret Scanning", policyPack: "ISO 27001 Base", severity: "critical", status: "fail", detail: "Gitleaks detected EXPORT_ENCRYPTION_KEY in src/export/config.go line 34.", automatedCheck: true },
    { id: "eval-001-5", controlId: "GDPR-1", controlName: "Data Minimization", policyPack: "GDPR Data Pack", severity: "critical", status: "warning", detail: "Export endpoint returns all patient fields. Field-level scoping required.", automatedCheck: true },
    { id: "eval-001-6", controlId: "CHANGE-1", controlName: "Change Management Process", policyPack: "ISO 27001 Base", severity: "medium", status: "pass", detail: "PR references JIRA-8847. Design doc linked.", automatedCheck: true },
    { id: "eval-001-7", controlId: "OWN-1", controlName: "Code Owner Review", policyPack: "ISO 27001 Base", severity: "high", status: "manual-required", detail: "bob.tngl.sh approval pending for api/** path ownership.", automatedCheck: true },
    { id: "eval-001-8", controlId: "GDPR-3", controlName: "Security of Processing", policyPack: "GDPR Data Pack", severity: "critical", status: "pass", detail: "TLS enforced on endpoint. Auth middleware present.", automatedCheck: true },
    { id: "eval-001-9", controlId: "AUDIT-1", controlName: "Audit Log Immutability", policyPack: "ISO 27001 Base", severity: "high", status: "pass", detail: "Assessment written to AT Protocol audit log.", automatedCheck: true },
    { id: "eval-001-10", controlId: "DOC-1", controlName: "Change Documented", policyPack: "ISO 27001 Base", severity: "low", status: "pass", detail: "JIRA-8847 linked in PR description.", automatedCheck: true },
    { id: "eval-001-11", controlId: "ACCESS-1", controlName: "Access Control Policy", policyPack: "ISO 27001 Base", severity: "high", status: "pass", detail: "Authentication guard present on export endpoint.", automatedCheck: false },
    { id: "eval-001-12", controlId: "GDPR-8", controlName: "Encryption at Rest", policyPack: "GDPR Data Pack", severity: "critical", status: "warning", detail: "Exported CSV not encrypted. Must use approved encryption before sending.", automatedCheck: true },
  ],
  requiredApprovals: [
    { id: "req-001-1", approverHandle: "bob.tngl.sh", approverDid: "did:plc:bob8yn3kqtr7plm55def", reason: "Code Owner for api/** path", obtained: false },
    { id: "req-001-2", approverHandle: "carol.tngl.sh", approverDid: "did:plc:carol9zp4lrus8qmn66ghi", reason: "DPO approval required for PII processing changes (GDPR-7)", obtained: false },
  ],
  evidence: {
    sast: {
      tool: "Semgrep",
      findings: [
        { rule: "secrets.hardcoded-key", severity: "critical", file: "src/export/config.go", line: 34, message: "Hardcoded encryption key EXPORT_ENCRYPTION_KEY detected. Use environment variable or secrets manager." },
        { rule: "csv.unsafe-parsing", severity: "medium", file: "src/export/handler.go", line: 112, message: "Unsafe CSV parsing with user-controlled input. Use csv.Reader with field validation." },
      ],
      totalCount: 2,
      runAt: "2026-06-24T08:25:00Z",
    },
    secrets: { tool: "Gitleaks", clean: false, findings: 1, runAt: "2026-06-24T08:26:00Z" },
    deps: {
      tool: "OSV Scanner",
      vulns: [{ id: "CVE-2024-38517", package: "csv-lib@1.2.0", severity: "critical", fixedIn: "1.2.4" }],
      totalVulns: 1,
      runAt: "2026-06-24T08:27:00Z",
    },
    aiReasoning: {
      model: "compliance-agent-v0.1.0",
      summary: "This PR introduces a patient data export endpoint with multiple critical compliance violations. The hardcoded EXPORT_ENCRYPTION_KEY is a severe secret leak that must be remediated immediately. The critical CVE in csv-lib could allow CSV injection attacks against exported patient data. DPO review is mandatory under GDPR-7 for any PII processing changes. Recommend blocking merge until all critical findings are resolved and carol.tngl.sh (DPO) has approved.",
      riskFactors: ["Hardcoded encryption key in source code", "Critical CVE in csv-lib@1.2.0", "DPO approval not obtained", "Export endpoint returns unfiltered PII fields", "Linked to open incident INC-7"],
      runAt: "2026-06-24T08:29:00Z",
    },
  },
  impactAssessment: {
    prId: "pr-001",
    riskLevel: "high",
    summary: "The patient export endpoint creates API dependencies in billing-service and triggers events consumed by auth-service. Both downstream services will be affected if the CSV format or encryption approach changes.",
    affectedEdges: [
      {
        downstreamRepoSlug: "billing-service",
        downstreamRepoName: "billing-service",
        sourcePath: "src/export/handler.go",
        targetPath: "src/billing/patient-data.ts",
        dependencyType: "api-call",
        reason: "billing-service calls patient export API to generate invoices with patient details",
        actionRequired: "update-required",
      },
      {
        downstreamRepoSlug: "auth-service",
        downstreamRepoName: "auth-service",
        sourcePath: "src/export/events.go",
        targetPath: "src/auth/patient-events.go",
        dependencyType: "event-consumer",
        reason: "auth-service listens for patient.export.completed events to enforce access revocation",
        actionRequired: "review-recommended",
      },
    ],
  },
  agentRun: {
    version: "0.1.0",
    durationMs: 14200,
    claudeTokensIn: 2847,
    claudeTokensOut: 512,
    scansRun: ["semgrep", "gitleaks", "osv-scanner", "impact-graph"],
    recordsWritten: 7,
    startedAt: "2026-06-24T08:16:00Z",
    completedAt: "2026-06-24T08:30:22Z",
  },
};

const assessment002: PRAssessment = {
  id: "assess-002",
  prId: "pr-002",
  assessedAt: "2026-06-23T14:00:00Z",
  assessedBy: "did:plc:agent7xcompliancerunner22abc",
  mergeGate: "pass",
  riskTier: "medium",
  riskSummary: "Stripe SDK upgrade from v11 to v12. All 12 controls pass. No PII changes, no new CVEs, no secrets found. Safe to merge.",
  complianceScore: 97,
  controlEvaluations: [
    { id: "eval-002-1", controlId: "VULN-1", controlName: "Dependency Vulnerability Scan", policyPack: "ISO 27001 Base", severity: "critical", status: "pass", detail: "stripe@12.0.0 has no known CVEs.", automatedCheck: true },
    { id: "eval-002-2", controlId: "VULN-2", controlName: "SAST Scan Required", policyPack: "ISO 27001 Base", severity: "high", status: "pass", detail: "Semgrep: 0 findings.", automatedCheck: true },
    { id: "eval-002-3", controlId: "VULN-3", controlName: "Secret Scanning", policyPack: "ISO 27001 Base", severity: "critical", status: "pass", detail: "Gitleaks: clean. No secrets found.", automatedCheck: true },
    { id: "eval-002-4", controlId: "CHANGE-1", controlName: "Change Management Process", policyPack: "ISO 27001 Base", severity: "medium", status: "pass", detail: "References JIRA-9102. Stripe SDK v12 migration doc attached.", automatedCheck: true },
    { id: "eval-002-5", controlId: "OWN-1", controlName: "Code Owner Review", policyPack: "ISO 27001 Base", severity: "high", status: "pass", detail: "alice.tngl.sh (owner) approved.", automatedCheck: true },
    { id: "eval-002-6", controlId: "ACCESS-1", controlName: "Access Control Policy", policyPack: "ISO 27001 Base", severity: "high", status: "pass", detail: "No access control changes.", automatedCheck: false },
    { id: "eval-002-7", controlId: "ACCESS-2", controlName: "Least Privilege Enforcement", policyPack: "ISO 27001 Base", severity: "high", status: "pass", detail: "Stripe API key scopes unchanged.", automatedCheck: true },
    { id: "eval-002-8", controlId: "CHANGE-2", controlName: "Rollback Capability", policyPack: "ISO 27001 Base", severity: "medium", status: "pass", detail: "package-lock.json pinned. Rollback documented in PR.", automatedCheck: false },
    { id: "eval-002-9", controlId: "CLASS-1", controlName: "Data Classification Required", policyPack: "ISO 27001 Base", severity: "medium", status: "pass", detail: "Repo classified as Confidential.", automatedCheck: false },
    { id: "eval-002-10", controlId: "DOC-1", controlName: "Change Documented", policyPack: "ISO 27001 Base", severity: "low", status: "pass", detail: "JIRA-9102 linked.", automatedCheck: true },
    { id: "eval-002-11", controlId: "AUDIT-1", controlName: "Audit Log Immutability", policyPack: "ISO 27001 Base", severity: "high", status: "pass", detail: "Assessment written to AT Protocol audit log.", automatedCheck: true },
    { id: "eval-002-12", controlId: "OWN-2", controlName: "Security Lead Approval for Auth Changes", policyPack: "ISO 27001 Base", severity: "high", status: "pass", detail: "No auth path changes. OWN-2 not triggered.", automatedCheck: true },
  ],
  requiredApprovals: [
    { id: "req-002-1", approverHandle: "alice.tngl.sh", approverDid: "did:plc:alice7xmq2kltrs9pnv44abc", reason: "Repo owner approval for high-risk tier repository", obtained: true, obtainedAt: "2026-06-23T15:30:00Z" },
  ],
  evidence: {
    sast: { tool: "Semgrep", findings: [], totalCount: 0, runAt: "2026-06-23T13:55:00Z" },
    secrets: { tool: "Gitleaks", clean: true, findings: 0, runAt: "2026-06-23T13:56:00Z" },
    deps: { tool: "OSV Scanner", vulns: [], totalVulns: 0, runAt: "2026-06-23T13:57:00Z" },
    aiReasoning: {
      model: "compliance-agent-v0.1.0",
      summary: "Routine SDK upgrade with clean scans. stripe@12 introduces webhook signature verification improvements which is a net security positive. No PII processing changes. Safe to merge.",
      riskFactors: [],
      runAt: "2026-06-23T13:59:00Z",
    },
  },
  agentRun: {
    version: "0.1.0",
    durationMs: 9800,
    claudeTokensIn: 1923,
    claudeTokensOut: 287,
    scansRun: ["semgrep", "gitleaks", "osv-scanner"],
    recordsWritten: 5,
    startedAt: "2026-06-23T13:50:00Z",
    completedAt: "2026-06-23T14:00:20Z",
  },
};

const assessment003: PRAssessment = {
  id: "assess-003",
  prId: "pr-003",
  assessedAt: "2026-06-22T10:00:00Z",
  assessedBy: "did:plc:agent7xcompliancerunner22abc",
  mergeGate: "needs-human-review",
  riskTier: "high",
  riskSummary: "2FA enrollment endpoint touches authentication paths. OWN-2 requires security-lead approval before merge. 11/12 controls pass. Technical implementation is sound but policy mandates explicit security-lead sign-off on all auth changes.",
  complianceScore: 78,
  controlEvaluations: [
    { id: "eval-003-1", controlId: "OWN-2", controlName: "Security Lead Approval for Auth Changes", policyPack: "ISO 27001 Base", severity: "high", status: "manual-required", detail: "2FA enrollment endpoint modifies authentication flow. carol.tngl.sh (security-lead) approval required.", automatedCheck: true },
    { id: "eval-003-2", controlId: "VULN-1", controlName: "Dependency Vulnerability Scan", policyPack: "ISO 27001 Base", severity: "critical", status: "pass", detail: "OSV scan: 0 vulnerabilities found.", automatedCheck: true },
    { id: "eval-003-3", controlId: "VULN-2", controlName: "SAST Scan Required", policyPack: "ISO 27001 Base", severity: "high", status: "pass", detail: "Semgrep: 0 findings.", automatedCheck: true },
    { id: "eval-003-4", controlId: "VULN-3", controlName: "Secret Scanning", policyPack: "ISO 27001 Base", severity: "critical", status: "pass", detail: "Gitleaks: clean.", automatedCheck: true },
    { id: "eval-003-5", controlId: "CHANGE-1", controlName: "Change Management Process", policyPack: "ISO 27001 Base", severity: "medium", status: "pass", detail: "References JIRA-9201.", automatedCheck: true },
    { id: "eval-003-6", controlId: "ACCESS-2", controlName: "Least Privilege Enforcement", policyPack: "ISO 27001 Base", severity: "high", status: "pass", detail: "2FA enrollment scoped to authenticated user only.", automatedCheck: true },
    { id: "eval-003-7", controlId: "DOC-1", controlName: "Change Documented", policyPack: "ISO 27001 Base", severity: "low", status: "pass", detail: "JIRA-9201 linked.", automatedCheck: true },
    { id: "eval-003-8", controlId: "AUDIT-1", controlName: "Audit Log Immutability", policyPack: "ISO 27001 Base", severity: "high", status: "pass", detail: "Assessment written to AT Protocol audit log.", automatedCheck: true },
    { id: "eval-003-9", controlId: "CLASS-1", controlName: "Data Classification Required", policyPack: "ISO 27001 Base", severity: "medium", status: "pass", detail: "Repo classified as Internal.", automatedCheck: false },
    { id: "eval-003-10", controlId: "CHANGE-2", controlName: "Rollback Capability", policyPack: "ISO 27001 Base", severity: "medium", status: "pass", detail: "Migration is additive. Rollback plan documented.", automatedCheck: false },
    { id: "eval-003-11", controlId: "OWN-1", controlName: "Code Owner Review", policyPack: "ISO 27001 Base", severity: "high", status: "pass", detail: "carol.tngl.sh is code owner for endpoints/**.", automatedCheck: true },
    { id: "eval-003-12", controlId: "ACCESS-1", controlName: "Access Control Policy", policyPack: "ISO 27001 Base", severity: "high", status: "pass", detail: "Auth guards verified on enrollment endpoint.", automatedCheck: false },
  ],
  requiredApprovals: [
    { id: "req-003-1", approverHandle: "carol.tngl.sh", approverDid: "did:plc:carol9zp4lrus8qmn66ghi", reason: "Security Lead approval required for auth-service changes (OWN-2)", obtained: false },
  ],
  evidence: {
    sast: { tool: "Semgrep", findings: [], totalCount: 0, runAt: "2026-06-22T09:55:00Z" },
    secrets: { tool: "Gitleaks", clean: true, findings: 0, runAt: "2026-06-22T09:55:00Z" },
    deps: { tool: "OSV Scanner", vulns: [], totalVulns: 0, runAt: "2026-06-22T09:55:00Z" },
    aiReasoning: {
      model: "compliance-agent-v0.1.0",
      summary: "2FA enrollment implementation is technically solid. TOTP secret generation uses crypto/rand, QR code generation is handled server-side, and backup codes are properly hashed. The only blocker is the policy-level requirement for security-lead approval on auth changes, not a technical deficiency.",
      riskFactors: ["Auth endpoint modification requires security-lead review per org policy"],
      runAt: "2026-06-22T09:58:00Z",
    },
  },
  agentRun: {
    version: "0.1.0",
    durationMs: 11400,
    claudeTokensIn: 2241,
    claudeTokensOut: 398,
    scansRun: ["semgrep", "gitleaks", "osv-scanner"],
    recordsWritten: 6,
    startedAt: "2026-06-22T09:48:00Z",
    completedAt: "2026-06-22T10:00:24Z",
  },
};

// ─── Pull Requests ────────────────────────────────────────────────────────────

export const mockPRs: PullRequest[] = [
  {
    id: "pr-001",
    number: 142,
    title: "feat: add patient export endpoint for GDPR data portability",
    description: "Implements GDPR Art. 20 data portability export for patients. Returns full patient record as encrypted CSV. References JIRA-8847.",
    repoId: "repo-001",
    repoSlug: "patient-service",
    authorId: "member-002",
    authorHandle: "bob.tngl.sh",
    baseBranch: "main",
    headBranch: "feat/patient-export",
    status: "open",
    createdAt: "2026-06-23T15:00:00Z",
    updatedAt: "2026-06-24T09:15:00Z",
    additions: 445,
    deletions: 12,
    changedFiles: 8,
    labels: ["gdpr", "pii", "blocked"],
    assessment: assessment001,
  },
  {
    id: "pr-002",
    number: 89,
    title: "chore: update Stripe SDK to v12",
    description: "Upgrades stripe from v11 to v12 following official migration guide. No breaking changes to billing flow. References JIRA-9102.",
    repoId: "repo-002",
    repoSlug: "billing-service",
    authorId: "member-002",
    authorHandle: "bob.tngl.sh",
    baseBranch: "main",
    headBranch: "chore/stripe-v12",
    status: "open",
    createdAt: "2026-06-23T09:00:00Z",
    updatedAt: "2026-06-23T14:00:00Z",
    additions: 203,
    deletions: 187,
    changedFiles: 6,
    labels: ["dependencies", "billing"],
    assessment: assessment002,
  },
  {
    id: "pr-003",
    number: 67,
    title: "feat: add 2FA enrollment endpoint",
    description: "Implements TOTP-based 2FA enrollment with QR code generation. Backup codes stored as bcrypt hashes. References JIRA-9201.",
    repoId: "repo-003",
    repoSlug: "auth-service",
    authorId: "member-002",
    authorHandle: "bob.tngl.sh",
    baseBranch: "main",
    headBranch: "feat/2fa-enrollment",
    status: "open",
    createdAt: "2026-06-22T09:00:00Z",
    updatedAt: "2026-06-22T11:00:00Z",
    additions: 312,
    deletions: 31,
    changedFiles: 7,
    labels: ["auth", "security", "needs-review"],
    assessment: assessment003,
  },
];

// ─── Issues ───────────────────────────────────────────────────────────────────

export const mockIssues: Issue[] = [
  {
    id: "ISS-1",
    did: "at://did:plc:acmehealth7x2kqmn9pltrs44e/sh.tangled.issue/ISS-1",
    number: 1,
    title: "Critical CVE in csv-lib@1.2.0 — patient export endpoint at risk of PII exfiltration",
    description: "Critical vulnerability CVE-2024-38517 (CVSS 9.8) detected in csv-lib@1.2.0 used by the new patient data export endpoint in PR #142. This vulnerability allows CSV injection attacks that could lead to patient PII exfiltration. Additionally, Gitleaks detected a hardcoded EXPORT_ENCRYPTION_KEY in src/export/config.go line 34. Both issues must be resolved before the PR can merge. Upgrade csv-lib to 1.2.4 and move the key to a secrets manager.",
    repoId: "repo-001",
    repoSlug: "patient-service",
    severity: "critical",
    category: "data-leak",
    affectedPackage: "csv-lib@1.2.0",
    cveIds: ["CVE-2024-38517"],
    assigneeHandle: "bob.tngl.sh",
    linkedPRId: "pr-001",
    status: "open",
    sla: {
      status: "open",
      deadline: "2026-06-26T20:00:00Z",
      hoursRemaining: 14,
      maxResolutionHours: 48,
      escalationAfterHours: 24,
      resolvedAt: undefined,
      resolvedBy: undefined,
    },
    createdAt: "2026-06-24T08:30:00Z",
    createdByHandle: "carol.tngl.sh",
  },
  {
    id: "ISS-2",
    did: "at://did:plc:acmehealth7x2kqmn9pltrs44e/sh.tangled.issue/ISS-2",
    number: 2,
    title: "Stripe SDK v12 webhook signature verification must be validated in staging",
    description: "Stripe SDK v12 changes the webhook signature verification algorithm. All existing webhook handlers in billing-service must be validated end-to-end in staging before PR #89 is merged to main and promoted to production. A misconfigured webhook could allow unauthorised payment events to be accepted.",
    repoId: "repo-002",
    repoSlug: "billing-service",
    severity: "medium",
    category: "misconfiguration",
    affectedPackage: "stripe@12.0.0",
    cveIds: [],
    assigneeHandle: "alice.tngl.sh",
    linkedPRId: "pr-002",
    status: "in-progress",
    sla: {
      status: "open",
      deadline: "2026-06-28T09:00:00Z",
      hoursRemaining: 72,
      maxResolutionHours: 120,
      escalationAfterHours: 72,
      resolvedAt: undefined,
      resolvedBy: undefined,
    },
    createdAt: "2026-06-23T14:05:00Z",
    createdByHandle: "bob.tngl.sh",
  },
  {
    id: "ISS-3",
    did: "at://did:plc:acmehealth7x2kqmn9pltrs44e/sh.tangled.issue/ISS-3",
    number: 3,
    title: "Security lead approval pending for 2FA enrollment endpoint — OWN-2 blocking merge",
    description: "The 2FA enrollment endpoint in auth-service PR #67 modifies authentication paths. Control OWN-2 requires explicit security-lead review before any auth changes can be merged. carol.tngl.sh must review the TOTP secret generation, QR code handling, backup code hashing (bcrypt), and confirm no auth-path regressions. Merge is blocked until approval is recorded on the AT Protocol compliance record.",
    repoId: "repo-003",
    repoSlug: "auth-service",
    severity: "high",
    category: "unauthorized-access",
    affectedPackage: undefined,
    cveIds: [],
    assigneeHandle: "carol.tngl.sh",
    linkedPRId: "pr-003",
    status: "open",
    sla: {
      status: "at-risk",
      deadline: "2026-06-27T09:00:00Z",
      hoursRemaining: 48,
      maxResolutionHours: 168,
      escalationAfterHours: 72,
      resolvedAt: undefined,
      resolvedBy: undefined,
    },
    createdAt: "2026-06-22T10:05:00Z",
    createdByHandle: "alice.tngl.sh",
  },
];

// ─── Audit Log ────────────────────────────────────────────────────────────────

export const mockAuditEntries: AuditEntry[] = [
  {
    id: "audit-001",
    type: "merge-gate",
    description: "Merge gate BLOCKED on patient-service#142 — critical GDPR + CVE violations",
    actorHandle: "compliance-agent.tngl.sh",
    actorDid: "did:plc:agent7xcompliancerunner22abc",
    targetType: "pr",
    targetId: "pr-001",
    targetLabel: "patient-service#142",
    metadata: { gate: "blocked", failedControls: 4, criticalFindings: 2, linkedIncident: "INC-7" },
    createdAt: "2026-06-24T08:30:00Z",
  },
  {
    id: "audit-002",
    type: "agent-run",
    description: "Compliance agent v0.1.0 completed assessment for patient-service#142",
    actorHandle: "compliance-agent.tngl.sh",
    actorDid: "did:plc:agent7xcompliancerunner22abc",
    targetType: "pr",
    targetId: "pr-001",
    targetLabel: "patient-service#142",
    metadata: { version: "0.1.0", durationMs: 14200, tokensIn: 2847, tokensOut: 512, recordsWritten: 7 },
    createdAt: "2026-06-24T08:30:22Z",
  },
  {
    id: "audit-003",
    type: "evidence",
    description: "Gitleaks detected EXPORT_ENCRYPTION_KEY in patient-service#142",
    actorHandle: "gitleaks-agent.tngl.sh",
    actorDid: "did:plc:agentbbgitleaks66mno",
    targetType: "pr",
    targetId: "pr-001",
    targetLabel: "patient-service#142",
    metadata: { tool: "Gitleaks", findings: 1, clean: false, file: "src/export/config.go", line: 34 },
    createdAt: "2026-06-24T08:26:00Z",
  },
  {
    id: "audit-004",
    type: "evidence",
    description: "OSV Scanner detected CVE-2024-38517 in csv-lib@1.2.0 (patient-service#142)",
    actorHandle: "osv-agent.tngl.sh",
    actorDid: "did:plc:agent9zosvscanner44ghi",
    targetType: "pr",
    targetId: "pr-001",
    targetLabel: "patient-service#142",
    metadata: { vulns: 1, critical: 1, high: 0, medium: 0, cve: "CVE-2024-38517" },
    createdAt: "2026-06-24T08:27:00Z",
  },
  {
    id: "audit-005",
    type: "assessment",
    description: "INC-7 created: critical CVE in patient-service linked to pr-001",
    actorHandle: "compliance-agent.tngl.sh",
    actorDid: "did:plc:agent7xcompliancerunner22abc",
    targetType: "repo",
    targetId: "repo-001",
    targetLabel: "patient-service",
    metadata: { incident: "INC-7", severity: "critical", cve: "CVE-2024-38517", slaHours: 48 },
    createdAt: "2026-06-24T08:31:00Z",
  },
  {
    id: "audit-006",
    type: "assessment",
    description: "Compliance assessment PASS for billing-service#89 (Stripe SDK v12)",
    actorHandle: "compliance-agent.tngl.sh",
    actorDid: "did:plc:agent7xcompliancerunner22abc",
    targetType: "pr",
    targetId: "pr-002",
    targetLabel: "billing-service#89",
    metadata: { mergeGate: "pass", score: 97, controlsEvaluated: 12 },
    createdAt: "2026-06-23T14:00:00Z",
  },
  {
    id: "audit-007",
    type: "member-action",
    description: "alice.tngl.sh approved billing-service#89 as repo owner",
    actorHandle: "alice.tngl.sh",
    actorDid: "did:plc:alice7xmq2kltrs9pnv44abc",
    targetType: "pr",
    targetId: "pr-002",
    targetLabel: "billing-service#89",
    metadata: { action: "approved", role: "owner" },
    createdAt: "2026-06-23T15:30:00Z",
  },
  {
    id: "audit-008",
    type: "merge-gate",
    description: "Merge gate NEEDS-HUMAN-REVIEW on auth-service#67 — OWN-2 pending carol.tngl.sh",
    actorHandle: "compliance-agent.tngl.sh",
    actorDid: "did:plc:agent7xcompliancerunner22abc",
    targetType: "pr",
    targetId: "pr-003",
    targetLabel: "auth-service#67",
    metadata: { gate: "needs-human-review", pendingApprover: "carol.tngl.sh", control: "OWN-2" },
    createdAt: "2026-06-22T10:00:00Z",
  },
  {
    id: "audit-009",
    type: "policy-change",
    description: "GDPR Data Pack bound to patient-service by carol.tngl.sh (DPO)",
    actorHandle: "carol.tngl.sh",
    actorDid: "did:plc:carol9zp4lrus8qmn66ghi",
    targetType: "policy",
    targetId: "pack-002",
    targetLabel: "GDPR Data Pack",
    metadata: { repo: "patient-service", action: "bind" },
    createdAt: "2026-06-01T10:00:00Z",
  },
  {
    id: "audit-010",
    type: "policy-change",
    description: "ISO 27001 Base pack updated to include OWN-2 security-lead approval control",
    actorHandle: "carol.tngl.sh",
    actorDid: "did:plc:carol9zp4lrus8qmn66ghi",
    targetType: "policy",
    targetId: "pack-001",
    targetLabel: "ISO 27001 Base",
    metadata: { action: "control-added", controlId: "OWN-2", addedBy: "carol.tngl.sh" },
    createdAt: "2026-06-18T11:00:00Z",
  },
];

// ─── Dependency Graph ─────────────────────────────────────────────────────────

export const mockDependencyGraph: DependencyGraph = {
  nodes: [
    { id: "node-001", repoId: "repo-001", repoSlug: "patient-service", label: "patient-service", complianceStatus: "non-compliant", riskTier: "high", x: 350, y: 110, critical: true },
    { id: "node-002", repoId: "repo-002", repoSlug: "billing-service", label: "billing-service", complianceStatus: "compliant", riskTier: "high", x: 160, y: 290, critical: true },
    { id: "node-003", repoId: "repo-003", repoSlug: "auth-service", label: "auth-service", complianceStatus: "at-risk", riskTier: "high", x: 540, y: 290, critical: true },
  ],
  edges: [
    { id: "edge-001", source: "node-001", target: "node-002", type: "depends-on", critical: true },
    { id: "edge-002", source: "node-003", target: "node-001", type: "integrates-with", critical: true },
    { id: "edge-003", source: "node-002", target: "node-003", type: "depends-on", critical: false },
  ],
};
