import type {
  Organization,
  Team,
  Member,
  Repo,
  PullRequest,
  PRAssessment,
  PolicyPack,
  Control,
  RepoBinding,
  AuditEntry,
  DependencyGraph,
} from "@/types";

// ─── Organization ───────────────────────────────────────────────────────────

export const mockOrg: Organization = {
  id: "org-001",
  did: "did:plc:acmecorp7x2kqmn9pltrs44e",
  handle: "acmecorp.bsky.social",
  name: "Acme Corp",
  description: "Building secure, compliant software at scale. Enterprise engineering org with focus on data privacy and regulatory compliance.",
  createdAt: "2023-06-15T10:00:00Z",
  stats: {
    repos: 6,
    members: 8,
    teams: 3,
    openPRs: 4,
  },
};

// ─── Teams ───────────────────────────────────────────────────────────────────

export const mockTeams: Team[] = [
  {
    id: "team-001",
    name: "Backend Platform",
    slug: "backend",
    description: "Core API services, authentication, and data infrastructure. Responsible for high-availability systems serving 10M+ users.",
    memberCount: 4,
    repoCount: 3,
    members: ["member-001", "member-002", "member-003", "member-004"],
    repos: ["repo-001", "repo-002", "repo-003"],
  },
  {
    id: "team-002",
    name: "Security & Compliance",
    slug: "security",
    description: "Threat modeling, vulnerability management, compliance automation, and security tooling.",
    memberCount: 2,
    repoCount: 2,
    members: ["member-005", "member-006"],
    repos: ["repo-004", "repo-005"],
  },
  {
    id: "team-003",
    name: "Data Platform",
    slug: "data-platform",
    description: "Data pipelines, ML infrastructure, analytics, and AI model deployment.",
    memberCount: 2,
    repoCount: 1,
    members: ["member-007", "member-008"],
    repos: ["repo-006"],
  },
];

// ─── Members ─────────────────────────────────────────────────────────────────

export const mockMembers: Member[] = [
  {
    id: "member-001",
    did: "did:plc:elena7xmq2kltrs9pnv44abc",
    handle: "elena.dev.bsky.social",
    displayName: "Elena Vasquez",
    role: "owner",
    teams: ["team-001"],
    lastActive: "2026-06-24T09:15:00Z",
    approvalCount: 47,
  },
  {
    id: "member-002",
    did: "did:plc:marcus8yn3kqtr7plm55def",
    handle: "mchen.bsky.social",
    displayName: "Marcus Chen",
    role: "maintainer",
    teams: ["team-001"],
    lastActive: "2026-06-23T16:42:00Z",
    approvalCount: 31,
  },
  {
    id: "member-003",
    did: "did:plc:priya9zp4lrus8qmn66ghi",
    handle: "priya.bsky.social",
    displayName: "Priya Patel",
    role: "developer",
    teams: ["team-001"],
    lastActive: "2026-06-24T08:00:00Z",
    approvalCount: 22,
  },
  {
    id: "member-004",
    did: "did:plc:james0aq5msvt9ron77jkl",
    handle: "jkim.dev.bsky.social",
    displayName: "James Kim",
    role: "developer",
    teams: ["team-001"],
    lastActive: "2026-06-22T11:30:00Z",
    approvalCount: 15,
  },
  {
    id: "member-005",
    did: "did:plc:sarah1br6ntwu0spo88mno",
    handle: "sarah.sec.bsky.social",
    displayName: "Sarah Okonkwo",
    role: "admin",
    teams: ["team-002"],
    lastActive: "2026-06-24T10:00:00Z",
    approvalCount: 89,
  },
  {
    id: "member-006",
    did: "did:plc:alex2cs7ouzv1tqp99pqr",
    handle: "alex.bsky.social",
    displayName: "Alex Rivera",
    role: "maintainer",
    teams: ["team-002"],
    lastActive: "2026-06-23T14:20:00Z",
    approvalCount: 56,
  },
  {
    id: "member-007",
    did: "did:plc:nina3dt8pvwa2urq00rst",
    handle: "nina.ml.bsky.social",
    displayName: "Nina Zhang",
    role: "maintainer",
    teams: ["team-003"],
    lastActive: "2026-06-24T07:45:00Z",
    approvalCount: 28,
  },
  {
    id: "member-008",
    did: "did:plc:tom4eu9qwxb3vsr11tuv",
    handle: "tom.bsky.social",
    displayName: "Tom Andersen",
    role: "developer",
    teams: ["team-003"],
    lastActive: "2026-06-21T09:00:00Z",
    approvalCount: 9,
  },
];

// ─── Repos ───────────────────────────────────────────────────────────────────

export const mockRepos: Repo[] = [
  {
    id: "repo-001",
    did: "did:plc:repo7xacme1apicore22abc",
    name: "api-core",
    slug: "api-core",
    description: "Core REST + GraphQL API gateway. Handles auth, rate limiting, and request routing for all customer-facing services.",
    language: "TypeScript",
    complianceStatus: "compliant",
    riskTier: "high",
    dataClassification: "confidential",
    stars: 142,
    forks: 23,
    openPRs: 1,
    lastActivity: "2026-06-24T09:15:00Z",
    policyPacks: ["pack-001", "pack-002", "pack-005"],
    regulations: ["GDPR", "SOC 2"],
    codeOwners: [
      { pattern: "**/*.ts", owners: ["@elena.dev.bsky.social", "@mchen.bsky.social"], teamOwners: ["@backend"] },
      { pattern: "src/auth/**", owners: ["@sarah.sec.bsky.social"], teamOwners: ["@security"] },
    ],
    teamId: "team-001",
  },
  {
    id: "repo-002",
    did: "did:plc:repo8yacme2userstore33def",
    name: "user-datastore",
    slug: "user-datastore",
    description: "PII storage layer with field-level encryption. Manages user profiles, preferences, and consent records.",
    language: "Go",
    complianceStatus: "compliant",
    riskTier: "critical",
    dataClassification: "restricted",
    stars: 88,
    forks: 12,
    openPRs: 1,
    lastActivity: "2026-06-23T16:42:00Z",
    policyPacks: ["pack-001", "pack-002", "pack-003"],
    regulations: ["GDPR", "HIPAA", "SOC 2"],
    codeOwners: [
      { pattern: "**", owners: ["@elena.dev.bsky.social"], teamOwners: ["@backend", "@security"] },
      { pattern: "migrations/**", owners: ["@sarah.sec.bsky.social", "@mchen.bsky.social"], teamOwners: [] },
    ],
    teamId: "team-001",
  },
  {
    id: "repo-003",
    did: "did:plc:repo9zacme3notifysvc44ghi",
    name: "notify-service",
    slug: "notify-service",
    description: "Async notification service for email, SMS, and push. Handles user communication preferences and opt-outs.",
    language: "TypeScript",
    complianceStatus: "at-risk",
    riskTier: "medium",
    dataClassification: "internal",
    stars: 34,
    forks: 5,
    openPRs: 2,
    lastActivity: "2026-06-22T11:30:00Z",
    policyPacks: ["pack-002", "pack-005"],
    regulations: ["GDPR"],
    codeOwners: [
      { pattern: "**", owners: ["@jkim.dev.bsky.social", "@priya.bsky.social"], teamOwners: ["@backend"] },
    ],
    teamId: "team-001",
  },
  {
    id: "repo-004",
    did: "did:plc:repo0aacme4sectools55jkl",
    name: "sec-tooling",
    slug: "sec-tooling",
    description: "Internal security automation: SAST runners, secret scanning, dependency auditing, and compliance reporting.",
    language: "Python",
    complianceStatus: "compliant",
    riskTier: "high",
    dataClassification: "confidential",
    stars: 29,
    forks: 3,
    openPRs: 0,
    lastActivity: "2026-06-24T10:00:00Z",
    policyPacks: ["pack-001", "pack-005"],
    regulations: ["SOC 2", "ISO 27001"],
    codeOwners: [
      { pattern: "**", owners: ["@sarah.sec.bsky.social", "@alex.bsky.social"], teamOwners: ["@security"] },
    ],
    teamId: "team-002",
  },
  {
    id: "repo-005",
    did: "did:plc:repo1bacme5vulnscanner66mno",
    name: "vuln-scanner",
    slug: "vuln-scanner",
    description: "OSV-based dependency vulnerability scanner with CVSS scoring and automated remediation PRs.",
    language: "Rust",
    complianceStatus: "compliant",
    riskTier: "medium",
    dataClassification: "internal",
    stars: 67,
    forks: 9,
    openPRs: 0,
    lastActivity: "2026-06-23T14:20:00Z",
    policyPacks: ["pack-001", "pack-005"],
    regulations: ["SOC 2"],
    codeOwners: [
      { pattern: "**", owners: ["@alex.bsky.social"], teamOwners: ["@security"] },
    ],
    teamId: "team-002",
  },
  {
    id: "repo-006",
    did: "did:plc:repo2cacme6mlpipeline77pqr",
    name: "ml-pipeline",
    slug: "ml-pipeline",
    description: "Training and inference pipeline for customer segmentation and churn prediction models. Contains LLM integration layer.",
    language: "Python",
    complianceStatus: "non-compliant",
    riskTier: "critical",
    dataClassification: "restricted",
    stars: 51,
    forks: 7,
    openPRs: 0,
    lastActivity: "2026-06-21T09:00:00Z",
    policyPacks: ["pack-004"],
    regulations: ["EU AI Act", "GDPR"],
    codeOwners: [
      { pattern: "**", owners: ["@nina.ml.bsky.social", "@tom.bsky.social"], teamOwners: ["@data-platform"] },
    ],
    teamId: "team-003",
  },
];

// ─── Controls ─────────────────────────────────────────────────────────────────

export const mockControls: Record<string, Control[]> = {
  "pack-001": [
    { id: "ctrl-001-1", name: "A.9.1 Access Control Policy", description: "Establish, document, and review access control policy.", severity: "high", automated: false, policyPackId: "pack-001", category: "Access Control", reference: "ISO 27001:2022 A.9.1" },
    { id: "ctrl-001-2", name: "A.12.6 Technical Vulnerability Management", description: "Identify and remediate technical vulnerabilities in a timely manner.", severity: "critical", automated: true, policyPackId: "pack-001", category: "Vulnerability Management", reference: "ISO 27001:2022 A.12.6" },
    { id: "ctrl-001-3", name: "A.14.2 Security in Dev Processes", description: "Security requirements for software development and support processes.", severity: "high", automated: true, policyPackId: "pack-001", category: "Secure Development", reference: "ISO 27001:2022 A.14.2" },
    { id: "ctrl-001-4", name: "A.8.3 Information Classification", description: "Classify information in terms of legal requirements, value, criticality.", severity: "medium", automated: false, policyPackId: "pack-001", category: "Asset Management", reference: "ISO 27001:2022 A.8.3" },
    { id: "ctrl-001-5", name: "A.10.1 Cryptography Controls", description: "Implement appropriate use of cryptographic controls.", severity: "high", automated: true, policyPackId: "pack-001", category: "Cryptography", reference: "ISO 27001:2022 A.10.1" },
  ],
  "pack-002": [
    { id: "ctrl-002-1", name: "Art. 5 Data Minimization", description: "Personal data collection limited to what is necessary.", severity: "critical", automated: false, policyPackId: "pack-002", category: "Data Processing", reference: "GDPR Art. 5(1)(c)" },
    { id: "ctrl-002-2", name: "Art. 25 Data Protection by Design", description: "Implement data protection by design and by default.", severity: "high", automated: false, policyPackId: "pack-002", category: "Privacy Engineering", reference: "GDPR Art. 25" },
    { id: "ctrl-002-3", name: "Art. 32 Security of Processing", description: "Implement appropriate technical and organizational security measures.", severity: "critical", automated: true, policyPackId: "pack-002", category: "Security", reference: "GDPR Art. 32" },
    { id: "ctrl-002-4", name: "Art. 17 Right to Erasure", description: "Implement mechanisms to fulfill data erasure requests.", severity: "high", automated: false, policyPackId: "pack-002", category: "Data Subject Rights", reference: "GDPR Art. 17" },
    { id: "ctrl-002-5", name: "Art. 33 Breach Notification", description: "Notify supervisory authority of personal data breaches within 72h.", severity: "critical", automated: false, policyPackId: "pack-002", category: "Incident Response", reference: "GDPR Art. 33" },
  ],
  "pack-003": [
    { id: "ctrl-003-1", name: "§164.312 Access Controls", description: "Implement technical policies limiting ePHI access to authorized persons.", severity: "critical", automated: true, policyPackId: "pack-003", category: "Access Control" },
    { id: "ctrl-003-2", name: "§164.312 Audit Controls", description: "Hardware, software, and procedural mechanisms to record access to ePHI.", severity: "high", automated: true, policyPackId: "pack-003", category: "Audit" },
    { id: "ctrl-003-3", name: "§164.312 Transmission Security", description: "Implement security measures guarding against unauthorized ePHI access.", severity: "critical", automated: true, policyPackId: "pack-003", category: "Transmission Security" },
  ],
  "pack-004": [
    { id: "ctrl-004-1", name: "Art. 9 Risk Management System", description: "Establish, implement, and maintain an AI risk management system.", severity: "critical", automated: false, policyPackId: "pack-004", category: "Risk Management", reference: "EU AI Act Art. 9" },
    { id: "ctrl-004-2", name: "Art. 10 Data Governance", description: "High-risk AI systems trained on data meeting quality criteria.", severity: "high", automated: false, policyPackId: "pack-004", category: "Data Governance", reference: "EU AI Act Art. 10" },
    { id: "ctrl-004-3", name: "Art. 13 Transparency", description: "High-risk AI systems designed with transparency to enable interpretation.", severity: "high", automated: false, policyPackId: "pack-004", category: "Transparency", reference: "EU AI Act Art. 13" },
    { id: "ctrl-004-4", name: "Art. 14 Human Oversight", description: "High-risk AI systems include human oversight measures.", severity: "critical", automated: false, policyPackId: "pack-004", category: "Human Oversight", reference: "EU AI Act Art. 14" },
    { id: "ctrl-004-5", name: "Art. 17 Quality Management", description: "Providers of high-risk AI systems shall implement QMS.", severity: "medium", automated: false, policyPackId: "pack-004", category: "Quality Management", reference: "EU AI Act Art. 17" },
  ],
  "pack-005": [
    { id: "ctrl-005-1", name: "CC6.1 Logical Access", description: "Implement logical access security software and infrastructure.", severity: "high", automated: true, policyPackId: "pack-005", category: "Logical Access", reference: "SOC 2 CC6.1" },
    { id: "ctrl-005-2", name: "CC7.1 System Monitoring", description: "Detect and monitor for configuration changes and security threats.", severity: "high", automated: true, policyPackId: "pack-005", category: "Monitoring", reference: "SOC 2 CC7.1" },
    { id: "ctrl-005-3", name: "CC8.1 Change Management", description: "Authorize, design, develop, and implement changes to infrastructure.", severity: "medium", automated: true, policyPackId: "pack-005", category: "Change Management", reference: "SOC 2 CC8.1" },
    { id: "ctrl-005-4", name: "CC9.1 Risk Mitigation", description: "Identify, select, and develop risk mitigation activities.", severity: "medium", automated: false, policyPackId: "pack-005", category: "Risk Assessment", reference: "SOC 2 CC9.1" },
    { id: "ctrl-005-5", name: "A1.1 Availability Monitoring", description: "Monitor availability commitments and system performance.", severity: "low", automated: true, policyPackId: "pack-005", category: "Availability", reference: "SOC 2 A1.1" },
  ],
};

// ─── Policy Packs ─────────────────────────────────────────────────────────────

export const mockPolicyPacks: PolicyPack[] = [
  {
    id: "pack-001",
    name: "ISO 27001:2022",
    framework: "ISO 27001",
    version: "2022",
    description: "International standard for information security management systems. Covers access control, cryptography, physical security, incident management, and more.",
    controlCount: 5,
    repoCount: 4,
    controls: mockControls["pack-001"],
    createdAt: "2023-09-01T00:00:00Z",
    updatedAt: "2025-01-15T00:00:00Z",
  },
  {
    id: "pack-002",
    name: "GDPR Compliance",
    framework: "GDPR",
    version: "2018",
    description: "EU General Data Protection Regulation controls for personal data handling, processing lawfulness, data subject rights, and breach notification.",
    controlCount: 5,
    repoCount: 4,
    controls: mockControls["pack-002"],
    createdAt: "2023-09-01T00:00:00Z",
    updatedAt: "2024-11-20T00:00:00Z",
  },
  {
    id: "pack-003",
    name: "HIPAA Security Rule",
    framework: "HIPAA",
    version: "2013",
    description: "HIPAA Security Rule technical safeguards for electronic protected health information (ePHI). Access controls, audit controls, integrity, transmission security.",
    controlCount: 3,
    repoCount: 1,
    controls: mockControls["pack-003"],
    createdAt: "2024-02-01T00:00:00Z",
    updatedAt: "2024-02-01T00:00:00Z",
  },
  {
    id: "pack-004",
    name: "EU AI Act",
    framework: "EU AI Act",
    version: "2024",
    description: "Controls for high-risk AI systems under the EU AI Act. Covers risk management, data governance, transparency requirements, human oversight, and quality management.",
    controlCount: 5,
    repoCount: 1,
    controls: mockControls["pack-004"],
    createdAt: "2024-08-01T00:00:00Z",
    updatedAt: "2025-03-10T00:00:00Z",
  },
  {
    id: "pack-005",
    name: "SOC 2 Type II",
    framework: "SOC 2",
    version: "2017",
    description: "AICPA SOC 2 Trust Service Criteria controls covering security, availability, processing integrity, confidentiality, and privacy.",
    controlCount: 5,
    repoCount: 4,
    controls: mockControls["pack-005"],
    createdAt: "2023-09-01T00:00:00Z",
    updatedAt: "2025-05-22T00:00:00Z",
  },
];

// ─── Repo Bindings ────────────────────────────────────────────────────────────

export const mockRepoBindings: RepoBinding[] = [
  { id: "bind-001", repoId: "repo-001", repoSlug: "api-core", policyPackId: "pack-001", policyPackName: "ISO 27001:2022", boundAt: "2023-10-01T00:00:00Z", boundBy: "@sarah.sec.bsky.social" },
  { id: "bind-002", repoId: "repo-001", repoSlug: "api-core", policyPackId: "pack-002", policyPackName: "GDPR Compliance", boundAt: "2023-10-01T00:00:00Z", boundBy: "@sarah.sec.bsky.social" },
  { id: "bind-003", repoId: "repo-001", repoSlug: "api-core", policyPackId: "pack-005", policyPackName: "SOC 2 Type II", boundAt: "2023-10-01T00:00:00Z", boundBy: "@sarah.sec.bsky.social" },
  { id: "bind-004", repoId: "repo-002", repoSlug: "user-datastore", policyPackId: "pack-001", policyPackName: "ISO 27001:2022", boundAt: "2023-10-01T00:00:00Z", boundBy: "@sarah.sec.bsky.social" },
  { id: "bind-005", repoId: "repo-002", repoSlug: "user-datastore", policyPackId: "pack-002", policyPackName: "GDPR Compliance", boundAt: "2023-10-01T00:00:00Z", boundBy: "@sarah.sec.bsky.social" },
  { id: "bind-006", repoId: "repo-002", repoSlug: "user-datastore", policyPackId: "pack-003", policyPackName: "HIPAA Security Rule", boundAt: "2024-03-01T00:00:00Z", boundBy: "@elena.dev.bsky.social" },
  { id: "bind-007", repoId: "repo-003", repoSlug: "notify-service", policyPackId: "pack-002", policyPackName: "GDPR Compliance", boundAt: "2024-01-15T00:00:00Z", boundBy: "@sarah.sec.bsky.social" },
  { id: "bind-008", repoId: "repo-003", repoSlug: "notify-service", policyPackId: "pack-005", policyPackName: "SOC 2 Type II", boundAt: "2024-01-15T00:00:00Z", boundBy: "@sarah.sec.bsky.social" },
  { id: "bind-009", repoId: "repo-004", repoSlug: "sec-tooling", policyPackId: "pack-001", policyPackName: "ISO 27001:2022", boundAt: "2023-10-01T00:00:00Z", boundBy: "@sarah.sec.bsky.social" },
  { id: "bind-010", repoId: "repo-004", repoSlug: "sec-tooling", policyPackId: "pack-005", policyPackName: "SOC 2 Type II", boundAt: "2023-10-01T00:00:00Z", boundBy: "@sarah.sec.bsky.social" },
  { id: "bind-011", repoId: "repo-005", repoSlug: "vuln-scanner", policyPackId: "pack-001", policyPackName: "ISO 27001:2022", boundAt: "2023-10-01T00:00:00Z", boundBy: "@alex.bsky.social" },
  { id: "bind-012", repoId: "repo-005", repoSlug: "vuln-scanner", policyPackId: "pack-005", policyPackName: "SOC 2 Type II", boundAt: "2023-10-01T00:00:00Z", boundBy: "@alex.bsky.social" },
  { id: "bind-013", repoId: "repo-006", repoSlug: "ml-pipeline", policyPackId: "pack-004", policyPackName: "EU AI Act", boundAt: "2024-09-01T00:00:00Z", boundBy: "@sarah.sec.bsky.social" },
];

// ─── Pull Request Assessments ─────────────────────────────────────────────────

const assessment001: PRAssessment = {
  id: "assess-001",
  prId: "pr-001",
  assessedAt: "2026-06-24T08:30:00Z",
  assessedBy: "did:plc:agent7xcompliancerunner22abc",
  mergeGate: "warning",
  riskTier: "high",
  riskSummary: "This PR introduces changes to the JWT token refresh logic and modifies rate-limiting middleware. The changes affect authentication flow for all API consumers. SAST detected 2 medium-severity findings related to token expiry validation. OSV found no new dependency vulnerabilities. Recommend security team review of the auth flow changes before merge.",
  complianceScore: 74,
  controlEvaluations: [
    { id: "eval-001-1", controlId: "ctrl-001-3", controlName: "A.14.2 Security in Dev Processes", policyPack: "ISO 27001:2022", severity: "high", status: "warning", detail: "Modified auth middleware requires security team sign-off per secure development policy.", automatedCheck: true },
    { id: "eval-001-2", controlId: "ctrl-005-3", controlName: "CC8.1 Change Management", policyPack: "SOC 2 Type II", severity: "medium", status: "pass", detail: "Change is documented in JIRA-4421. PR description references design doc.", automatedCheck: true },
    { id: "eval-001-3", controlId: "ctrl-001-2", controlName: "A.12.6 Technical Vulnerability Management", policyPack: "ISO 27001:2022", severity: "critical", status: "pass", detail: "OSV scan found 0 new vulnerabilities. Existing low-severity items tracked separately.", automatedCheck: true },
    { id: "eval-001-4", controlId: "ctrl-002-3", controlName: "Art. 32 Security of Processing", policyPack: "GDPR Compliance", severity: "critical", status: "warning", detail: "JWT changes affect encryption-at-rest guarantees. Needs data protection officer review.", automatedCheck: false },
    { id: "eval-001-5", controlId: "ctrl-001-5", controlName: "A.10.1 Cryptography Controls", policyPack: "ISO 27001:2022", severity: "high", status: "pass", detail: "Token signing uses RS256. Key rotation policy unchanged.", automatedCheck: true },
    { id: "eval-001-6", controlId: "ctrl-005-1", controlName: "CC6.1 Logical Access", policyPack: "SOC 2 Type II", severity: "high", status: "pass", detail: "No access control logic changes detected. Scope limited to token lifecycle.", automatedCheck: true },
  ],
  requiredApprovals: [
    { id: "req-001-1", teamSlug: "security", reason: "Auth middleware changes require security team approval per CODEOWNERS", obtained: false },
    { id: "req-001-2", approverHandle: "elena.dev.bsky.social", approverDid: "did:plc:elena7xmq2kltrs9pnv44abc", reason: "Repo owner approval required for high-risk tier repositories", obtained: true, obtainedAt: "2026-06-24T09:00:00Z" },
  ],
  evidence: {
    sast: {
      tool: "Semgrep",
      findings: [
        { rule: "jwt.decode-without-verify", severity: "medium", file: "src/auth/token.ts", line: 142, message: "JWT decoded without explicit verification of signature. Use jwt.verify() instead." },
        { rule: "jwt.weak-secret-fallback", severity: "medium", file: "src/auth/token.ts", line: 89, message: "Fallback to weak secret detected. Ensure JWT_SECRET is always set in production." },
      ],
      totalCount: 2,
      runAt: "2026-06-24T08:25:00Z",
    },
    secrets: {
      tool: "Gitleaks",
      clean: true,
      findings: 0,
      runAt: "2026-06-24T08:26:00Z",
    },
    deps: {
      tool: "OSV Scanner",
      vulns: [],
      totalVulns: 0,
      runAt: "2026-06-24T08:27:00Z",
    },
    aiReasoning: {
      model: "claude-3-5-sonnet-20241022",
      summary: "The PR modifies core authentication token handling. Changes are logically sound but introduce subtle risks: (1) the fallback JWT secret path could be exercised in misconfigured environments, (2) the refresh window extension from 15m to 30m increases session hijack exposure. These are not blockers but warrant security team review. No PII data flow changes detected. Dependency surface unchanged.",
      riskFactors: ["JWT secret fallback path introduced", "Session window extended (15m→30m)", "Auth middleware touched by non-security team member"],
      runAt: "2026-06-24T08:29:00Z",
    },
  },
};

const assessment002: PRAssessment = {
  id: "assess-002",
  prId: "pr-002",
  assessedAt: "2026-06-23T14:00:00Z",
  assessedBy: "did:plc:agent7xcompliancerunner22abc",
  mergeGate: "blocked",
  riskTier: "critical",
  riskSummary: "This PR adds a new user data export endpoint that returns raw PII fields including email, phone, location history, and payment methods in a single API response. Multiple critical GDPR and SOC 2 controls are failing. The endpoint lacks authentication guards, rate limiting, and audit logging. SAST found a SQL injection vulnerability. This PR must not be merged without remediation.",
  complianceScore: 23,
  controlEvaluations: [
    { id: "eval-002-1", controlId: "ctrl-002-1", controlName: "Art. 5 Data Minimization", policyPack: "GDPR Compliance", severity: "critical", status: "fail", detail: "Export endpoint returns all PII fields without filtering. Must implement field-level access scoping.", automatedCheck: true },
    { id: "eval-002-2", controlId: "ctrl-002-3", controlName: "Art. 32 Security of Processing", policyPack: "GDPR Compliance", severity: "critical", status: "fail", detail: "No authentication check on /api/export endpoint. Any unauthenticated user can access PII.", automatedCheck: true },
    { id: "eval-002-3", controlId: "ctrl-001-2", controlName: "A.12.6 Technical Vulnerability Management", policyPack: "ISO 27001:2022", severity: "critical", status: "fail", detail: "SQL injection vulnerability detected in query builder (SQLI-001). Must fix before merge.", automatedCheck: true },
    { id: "eval-002-4", controlId: "ctrl-005-1", controlName: "CC6.1 Logical Access", policyPack: "SOC 2 Type II", severity: "high", status: "fail", detail: "No authorization checks. Endpoint accessible without valid session token.", automatedCheck: true },
    { id: "eval-002-5", controlId: "ctrl-005-3", controlName: "CC8.1 Change Management", policyPack: "SOC 2 Type II", severity: "medium", status: "warning", detail: "No JIRA ticket linked. PR description does not reference design document.", automatedCheck: true },
    { id: "eval-002-6", controlId: "ctrl-002-4", controlName: "Art. 17 Right to Erasure", policyPack: "GDPR Compliance", severity: "high", status: "manual-required", detail: "Export functionality may conflict with erasure requests. DPO review required.", automatedCheck: false },
  ],
  requiredApprovals: [
    { id: "req-002-1", teamSlug: "security", reason: "Critical security findings require security team remediation and approval", obtained: false },
    { id: "req-002-2", approverHandle: "elena.dev.bsky.social", approverDid: "did:plc:elena7xmq2kltrs9pnv44abc", reason: "Critical-tier repo owner must approve PII-impacting changes", obtained: false },
  ],
  evidence: {
    sast: {
      tool: "Semgrep",
      findings: [
        { rule: "sqli.raw-query-concatenation", severity: "critical", file: "src/api/export.go", line: 78, message: "Raw SQL string concatenation with user input detected. Use parameterized queries." },
        { rule: "auth.missing-authentication", severity: "critical", file: "src/api/export.go", line: 12, message: "HTTP handler registered without authentication middleware." },
        { rule: "pii.logging-sensitive-data", severity: "high", file: "src/api/export.go", line: 156, message: "User email field logged at INFO level. Remove PII from logs." },
      ],
      totalCount: 3,
      runAt: "2026-06-23T13:55:00Z",
    },
    secrets: {
      tool: "Gitleaks",
      clean: true,
      findings: 0,
      runAt: "2026-06-23T13:56:00Z",
    },
    deps: {
      tool: "OSV Scanner",
      vulns: [
        { id: "GHSA-2vh5-xxxx-1234", package: "database/sql@v1.2.1", severity: "medium", fixedIn: "v1.2.3" },
      ],
      totalVulns: 1,
      runAt: "2026-06-23T13:57:00Z",
    },
    aiReasoning: {
      model: "claude-3-5-sonnet-20241022",
      summary: "This PR presents severe compliance risks and must be blocked. The unauthenticated PII export endpoint violates GDPR Art. 5 and Art. 32 at a fundamental level — this is not a configuration issue but an architectural flaw. Combined with the SQL injection vulnerability, this PR could expose the entire user database to exfiltration. The developer should be directed to the org's PII handling guidelines and the existing authenticated export flow in /internal/export/.",
      riskFactors: ["Unauthenticated PII endpoint", "SQL injection vulnerability", "No audit logging for data access", "Mass PII exposure (email, phone, location, payment)", "No rate limiting"],
      runAt: "2026-06-23T13:59:00Z",
    },
  },
};

const assessment003: PRAssessment = {
  id: "assess-003",
  prId: "pr-003",
  assessedAt: "2026-06-22T10:00:00Z",
  assessedBy: "did:plc:agent7xcompliancerunner22abc",
  mergeGate: "pass",
  riskTier: "low",
  riskSummary: "Documentation update only. No executable code changes detected. SAST, secret scanning, and dependency scanning not applicable. All compliance controls pass.",
  complianceScore: 98,
  controlEvaluations: [
    { id: "eval-003-1", controlId: "ctrl-005-3", controlName: "CC8.1 Change Management", policyPack: "SOC 2 Type II", severity: "medium", status: "pass", detail: "Change is documentation-only. Standard approval process applies.", automatedCheck: true },
    { id: "eval-003-2", controlId: "ctrl-001-3", controlName: "A.14.2 Security in Dev Processes", policyPack: "ISO 27001:2022", severity: "high", status: "pass", detail: "No executable code changes. Security review not required.", automatedCheck: true },
  ],
  requiredApprovals: [
    { id: "req-003-1", approverHandle: "jkim.dev.bsky.social", approverDid: "did:plc:james0aq5msvt9ron77jkl", reason: "Standard PR approval required", obtained: true, obtainedAt: "2026-06-22T11:00:00Z" },
  ],
  evidence: {
    sast: { tool: "Semgrep", findings: [], totalCount: 0, runAt: "2026-06-22T09:55:00Z" },
    secrets: { tool: "Gitleaks", clean: true, findings: 0, runAt: "2026-06-22T09:55:00Z" },
    deps: { tool: "OSV Scanner", vulns: [], totalVulns: 0, runAt: "2026-06-22T09:55:00Z" },
    aiReasoning: {
      model: "claude-3-5-sonnet-20241022",
      summary: "No code changes detected. This PR only modifies README.md and inline documentation comments. No compliance risk identified. Safe to merge after standard peer review.",
      riskFactors: [],
      runAt: "2026-06-22T09:58:00Z",
    },
  },
};

const assessment004: PRAssessment = {
  id: "assess-004",
  prId: "pr-004",
  assessedAt: "2026-06-24T07:45:00Z",
  assessedBy: "did:plc:agent7xcompliancerunner22abc",
  mergeGate: "needs-human-review",
  riskTier: "high",
  riskSummary: "Email template changes include new marketing opt-out handling. One GDPR control requires manual DPO review — the new unsubscribe flow must be verified to honor all consent records. SAST is clean. Technical implementation appears correct but legal sign-off on the consent mechanism is required per org policy.",
  complianceScore: 61,
  controlEvaluations: [
    { id: "eval-004-1", controlId: "ctrl-002-1", controlName: "Art. 5 Data Minimization", policyPack: "GDPR Compliance", severity: "critical", status: "pass", detail: "Email templates contain no PII beyond recipient address. Marketing data minimized.", automatedCheck: true },
    { id: "eval-004-2", controlId: "ctrl-002-2", controlName: "Art. 25 Data Protection by Design", policyPack: "GDPR Compliance", severity: "high", status: "manual-required", detail: "Consent mechanism changes require DPO sign-off. Legal review in progress.", automatedCheck: false },
    { id: "eval-004-3", controlId: "ctrl-005-3", controlName: "CC8.1 Change Management", policyPack: "SOC 2 Type II", severity: "medium", status: "pass", detail: "Linked to JIRA-5512. Approved in sprint planning.", automatedCheck: true },
  ],
  requiredApprovals: [
    { id: "req-004-1", approverHandle: "sarah.sec.bsky.social", approverDid: "did:plc:sarah1br6ntwu0spo88mno", reason: "GDPR consent mechanism changes require compliance officer review", obtained: false },
    { id: "req-004-2", approverHandle: "priya.bsky.social", approverDid: "did:plc:priya9zp4lrus8qmn66ghi", reason: "Code owner approval for notify-service", obtained: true, obtainedAt: "2026-06-24T08:30:00Z" },
  ],
  evidence: {
    sast: { tool: "Semgrep", findings: [], totalCount: 0, runAt: "2026-06-24T07:40:00Z" },
    secrets: { tool: "Gitleaks", clean: true, findings: 0, runAt: "2026-06-24T07:41:00Z" },
    deps: { tool: "OSV Scanner", vulns: [], totalVulns: 0, runAt: "2026-06-24T07:42:00Z" },
    aiReasoning: {
      model: "claude-3-5-sonnet-20241022",
      summary: "The new marketing consent flow looks technically sound. The unsubscribe token is properly hashed, expiry is set, and the consent table update is transactional. The human review requirement is a policy-level concern, not a technical flaw — org policy requires DPO sign-off on any changes to consent processing logic, regardless of technical quality.",
      riskFactors: ["Consent processing logic modified", "DPO review pending", "New unsubscribe token format (migration required)"],
      runAt: "2026-06-24T07:44:00Z",
    },
  },
};

// ─── Pull Requests ────────────────────────────────────────────────────────────

export const mockPRs: PullRequest[] = [
  {
    id: "pr-001",
    number: 247,
    title: "feat: refresh token rotation with sliding window expiry",
    description: "Implements sliding window token refresh to improve UX for long-running sessions. Extends refresh window from 15m to 30m and adds rotation logic to prevent replay attacks.",
    repoId: "repo-001",
    repoSlug: "api-core",
    authorId: "member-002",
    authorHandle: "mchen.bsky.social",
    baseBranch: "main",
    headBranch: "feat/token-refresh-v2",
    status: "open",
    createdAt: "2026-06-23T15:00:00Z",
    updatedAt: "2026-06-24T09:15:00Z",
    additions: 312,
    deletions: 87,
    changedFiles: 8,
    labels: ["auth", "security", "needs-review"],
    assessment: assessment001,
  },
  {
    id: "pr-002",
    number: 156,
    title: "feat: user data export endpoint for GDPR compliance",
    description: "Adds /api/v1/export endpoint to fulfill GDPR data portability requests. Returns full user record as JSON.",
    repoId: "repo-002",
    repoSlug: "user-datastore",
    authorId: "member-004",
    authorHandle: "jkim.dev.bsky.social",
    baseBranch: "main",
    headBranch: "feat/gdpr-export",
    status: "open",
    createdAt: "2026-06-23T09:00:00Z",
    updatedAt: "2026-06-23T14:00:00Z",
    additions: 445,
    deletions: 12,
    changedFiles: 6,
    labels: ["gdpr", "pii", "blocked"],
    assessment: assessment002,
  },
  {
    id: "pr-003",
    number: 89,
    title: "docs: update CODEOWNERS and contributing guide",
    description: "Updates CODEOWNERS to reflect new team structure. Adds section on compliance requirements for PRs.",
    repoId: "repo-003",
    repoSlug: "notify-service",
    authorId: "member-003",
    authorHandle: "priya.bsky.social",
    baseBranch: "main",
    headBranch: "docs/update-codeowners",
    status: "open",
    createdAt: "2026-06-22T09:00:00Z",
    updatedAt: "2026-06-22T11:00:00Z",
    additions: 47,
    deletions: 31,
    changedFiles: 2,
    labels: ["documentation"],
    assessment: assessment003,
  },
  {
    id: "pr-004",
    number: 91,
    title: "feat: marketing email consent v2 with token-based unsubscribe",
    description: "Replaces link-based unsubscribe with signed token mechanism. Adds consent audit trail to database.",
    repoId: "repo-003",
    repoSlug: "notify-service",
    authorId: "member-003",
    authorHandle: "priya.bsky.social",
    baseBranch: "main",
    headBranch: "feat/consent-v2",
    status: "open",
    createdAt: "2026-06-24T06:00:00Z",
    updatedAt: "2026-06-24T08:30:00Z",
    additions: 203,
    deletions: 56,
    changedFiles: 9,
    labels: ["gdpr", "consent", "needs-legal-review"],
    assessment: assessment004,
  },
];

// ─── Audit Log ────────────────────────────────────────────────────────────────

export const mockAuditEntries: AuditEntry[] = [
  {
    id: "audit-001",
    type: "assessment",
    description: "Compliance assessment completed for PR #247",
    actorHandle: "compliance-agent.bsky.social",
    actorDid: "did:plc:agent7xcompliancerunner22abc",
    targetType: "pr",
    targetId: "pr-001",
    targetLabel: "api-core#247",
    metadata: { mergeGate: "warning", score: 74, controlsEvaluated: 6 },
    createdAt: "2026-06-24T08:30:00Z",
  },
  {
    id: "audit-002",
    type: "agent-run",
    description: "SAST scan completed: 2 findings in api-core#247",
    actorHandle: "semgrep-agent.bsky.social",
    actorDid: "did:plc:agent8ysemgreprunner33def",
    targetType: "pr",
    targetId: "pr-001",
    targetLabel: "api-core#247",
    metadata: { tool: "Semgrep", findings: 2, duration_ms: 4821 },
    createdAt: "2026-06-24T08:25:00Z",
  },
  {
    id: "audit-003",
    type: "merge-gate",
    description: "Merge gate BLOCKED on user-datastore#156 — critical GDPR violations",
    actorHandle: "compliance-agent.bsky.social",
    actorDid: "did:plc:agent7xcompliancerunner22abc",
    targetType: "pr",
    targetId: "pr-002",
    targetLabel: "user-datastore#156",
    metadata: { gate: "blocked", failedControls: 4, criticalFindings: 3 },
    createdAt: "2026-06-23T14:00:00Z",
  },
  {
    id: "audit-004",
    type: "evidence",
    description: "OSV vulnerability report submitted for user-datastore#156",
    actorHandle: "osv-agent.bsky.social",
    actorDid: "did:plc:agent9zosvscanner44ghi",
    targetType: "pr",
    targetId: "pr-002",
    targetLabel: "user-datastore#156",
    metadata: { vulns: 1, critical: 0, high: 0, medium: 1 },
    createdAt: "2026-06-23T13:57:00Z",
  },
  {
    id: "audit-005",
    type: "assessment",
    description: "Compliance assessment completed for PR #91 — needs human review",
    actorHandle: "compliance-agent.bsky.social",
    actorDid: "did:plc:agent7xcompliancerunner22abc",
    targetType: "pr",
    targetId: "pr-004",
    targetLabel: "notify-service#91",
    metadata: { mergeGate: "needs-human-review", score: 61, controlsEvaluated: 3 },
    createdAt: "2026-06-24T07:45:00Z",
  },
  {
    id: "audit-006",
    type: "waiver",
    description: "Waiver granted for A.8.3 Information Classification on notify-service",
    actorHandle: "sarah.sec.bsky.social",
    actorDid: "did:plc:sarah1br6ntwu0spo88mno",
    targetType: "repo",
    targetId: "repo-003",
    targetLabel: "notify-service",
    metadata: { control: "A.8.3", duration_days: 30, reason: "Classification review in progress" },
    createdAt: "2026-06-22T16:00:00Z",
  },
  {
    id: "audit-007",
    type: "policy-change",
    description: "EU AI Act policy pack bound to ml-pipeline",
    actorHandle: "sarah.sec.bsky.social",
    actorDid: "did:plc:sarah1br6ntwu0spo88mno",
    targetType: "policy",
    targetId: "pack-004",
    targetLabel: "EU AI Act",
    metadata: { repo: "ml-pipeline", action: "bind" },
    createdAt: "2026-06-20T14:00:00Z",
  },
  {
    id: "audit-008",
    type: "agent-run",
    description: "Claude compliance reasoning completed for user-datastore#156",
    actorHandle: "claude-agent.bsky.social",
    actorDid: "did:plc:agentaaclaude55jkl",
    targetType: "pr",
    targetId: "pr-002",
    targetLabel: "user-datastore#156",
    metadata: { model: "claude-3-5-sonnet-20241022", tokens_used: 4192, duration_ms: 3201 },
    createdAt: "2026-06-23T13:59:00Z",
  },
  {
    id: "audit-009",
    type: "member-action",
    description: "Elena Vasquez approved PR #247 (api-core) as repo owner",
    actorHandle: "elena.dev.bsky.social",
    actorDid: "did:plc:elena7xmq2kltrs9pnv44abc",
    targetType: "pr",
    targetId: "pr-001",
    targetLabel: "api-core#247",
    metadata: { action: "approved", role: "owner" },
    createdAt: "2026-06-24T09:00:00Z",
  },
  {
    id: "audit-010",
    type: "evidence",
    description: "Gitleaks secret scan completed: no secrets found in api-core#247",
    actorHandle: "gitleaks-agent.bsky.social",
    actorDid: "did:plc:agentbbgitleaks66mno",
    targetType: "pr",
    targetId: "pr-001",
    targetLabel: "api-core#247",
    metadata: { tool: "Gitleaks", findings: 0, clean: true },
    createdAt: "2026-06-24T08:26:00Z",
  },
  {
    id: "audit-011",
    type: "policy-change",
    description: "SOC 2 Type II control pack updated to v2025.05",
    actorHandle: "sarah.sec.bsky.social",
    actorDid: "did:plc:sarah1br6ntwu0spo88mno",
    targetType: "policy",
    targetId: "pack-005",
    targetLabel: "SOC 2 Type II",
    metadata: { from_version: "2017", to_version: "2017-r2025", controls_changed: 2 },
    createdAt: "2026-06-18T11:00:00Z",
  },
  {
    id: "audit-012",
    type: "member-action",
    description: "Tom Andersen added to data-platform team",
    actorHandle: "elena.dev.bsky.social",
    actorDid: "did:plc:elena7xmq2kltrs9pnv44abc",
    targetType: "member",
    targetId: "member-008",
    targetLabel: "tom.bsky.social",
    metadata: { action: "team-add", team: "data-platform" },
    createdAt: "2026-06-15T09:30:00Z",
  },
  {
    id: "audit-013",
    type: "assessment",
    description: "Quarterly compliance scan: ml-pipeline flagged as non-compliant",
    actorHandle: "compliance-agent.bsky.social",
    actorDid: "did:plc:agent7xcompliancerunner22abc",
    targetType: "repo",
    targetId: "repo-006",
    targetLabel: "ml-pipeline",
    metadata: { score: 31, failedControls: 4, schedule: "quarterly" },
    createdAt: "2026-06-21T00:00:00Z",
  },
  {
    id: "audit-014",
    type: "waiver",
    description: "Waiver requested for Art. 14 Human Oversight on ml-pipeline — pending approval",
    actorHandle: "nina.ml.bsky.social",
    actorDid: "did:plc:nina3dt8pvwa2urq00rst",
    targetType: "repo",
    targetId: "repo-006",
    targetLabel: "ml-pipeline",
    metadata: { control: "Art. 14", status: "pending", justification: "Interim period while oversight tooling is built" },
    createdAt: "2026-06-21T10:00:00Z",
  },
  {
    id: "audit-015",
    type: "agent-run",
    description: "Dependency graph analysis completed: 3 critical path repos identified",
    actorHandle: "graph-agent.bsky.social",
    actorDid: "did:plc:agentccgraph77pqr",
    targetType: "org",
    targetId: "org-001",
    targetLabel: "Acme Corp",
    metadata: { nodes: 6, edges: 9, critical_paths: 3 },
    createdAt: "2026-06-23T00:00:00Z",
  },
  {
    id: "audit-016",
    type: "evidence",
    description: "SAST scan: 3 critical findings in user-datastore#156",
    actorHandle: "semgrep-agent.bsky.social",
    actorDid: "did:plc:agent8ysemgreprunner33def",
    targetType: "pr",
    targetId: "pr-002",
    targetLabel: "user-datastore#156",
    metadata: { tool: "Semgrep", findings: 3, critical: 2, high: 1 },
    createdAt: "2026-06-23T13:55:00Z",
  },
  {
    id: "audit-017",
    type: "policy-change",
    description: "HIPAA Security Rule pack bound to user-datastore",
    actorHandle: "elena.dev.bsky.social",
    actorDid: "did:plc:elena7xmq2kltrs9pnv44abc",
    targetType: "policy",
    targetId: "pack-003",
    targetLabel: "HIPAA Security Rule",
    metadata: { repo: "user-datastore", action: "bind" },
    createdAt: "2024-03-01T00:00:00Z",
  },
  {
    id: "audit-018",
    type: "member-action",
    description: "Priya Patel approved PR #91 (notify-service) as code owner",
    actorHandle: "priya.bsky.social",
    actorDid: "did:plc:priya9zp4lrus8qmn66ghi",
    targetType: "pr",
    targetId: "pr-004",
    targetLabel: "notify-service#91",
    metadata: { action: "approved", role: "code-owner" },
    createdAt: "2026-06-24T08:30:00Z",
  },
  {
    id: "audit-019",
    type: "merge-gate",
    description: "Merge gate PASS on notify-service#89 — documentation only change",
    actorHandle: "compliance-agent.bsky.social",
    actorDid: "did:plc:agent7xcompliancerunner22abc",
    targetType: "pr",
    targetId: "pr-003",
    targetLabel: "notify-service#89",
    metadata: { gate: "pass", score: 98 },
    createdAt: "2026-06-22T10:00:00Z",
  },
  {
    id: "audit-020",
    type: "assessment",
    description: "ISO 27001 spot audit triggered on sec-tooling by security team",
    actorHandle: "alex.bsky.social",
    actorDid: "did:plc:alex2cs7ouzv1tqp99pqr",
    targetType: "repo",
    targetId: "repo-004",
    targetLabel: "sec-tooling",
    metadata: { score: 96, trigger: "manual", requestedBy: "@alex.bsky.social" },
    createdAt: "2026-06-20T09:00:00Z",
  },
];

// ─── Dependency Graph ─────────────────────────────────────────────────────────

export const mockDependencyGraph: DependencyGraph = {
  nodes: [
    { id: "node-001", repoId: "repo-001", repoSlug: "api-core", label: "api-core", complianceStatus: "compliant", riskTier: "high", x: 400, y: 200, critical: true },
    { id: "node-002", repoId: "repo-002", repoSlug: "user-datastore", label: "user-datastore", complianceStatus: "compliant", riskTier: "critical", x: 200, y: 350, critical: true },
    { id: "node-003", repoId: "repo-003", repoSlug: "notify-service", label: "notify-service", complianceStatus: "at-risk", riskTier: "medium", x: 600, y: 350, critical: false },
    { id: "node-004", repoId: "repo-004", repoSlug: "sec-tooling", label: "sec-tooling", complianceStatus: "compliant", riskTier: "high", x: 100, y: 150, critical: false },
    { id: "node-005", repoId: "repo-005", repoSlug: "vuln-scanner", label: "vuln-scanner", complianceStatus: "compliant", riskTier: "medium", x: 700, y: 150, critical: false },
    { id: "node-006", repoId: "repo-006", repoSlug: "ml-pipeline", label: "ml-pipeline", complianceStatus: "non-compliant", riskTier: "critical", x: 400, y: 500, critical: true },
  ],
  edges: [
    { id: "edge-001", source: "node-001", target: "node-002", type: "depends-on", critical: true },
    { id: "edge-002", source: "node-001", target: "node-003", type: "depends-on", critical: false },
    { id: "edge-003", source: "node-001", target: "node-006", type: "integrates-with", critical: true },
    { id: "edge-004", source: "node-002", target: "node-006", type: "depends-on", critical: true },
    { id: "edge-005", source: "node-003", target: "node-002", type: "depends-on", critical: false },
    { id: "edge-006", source: "node-004", target: "node-001", type: "integrates-with", critical: false },
    { id: "edge-007", source: "node-004", target: "node-002", type: "integrates-with", critical: false },
    { id: "edge-008", source: "node-005", target: "node-001", type: "integrates-with", critical: false },
    { id: "edge-009", source: "node-005", target: "node-002", type: "integrates-with", critical: false },
  ],
};
